### ISSUE TITLE
Can't download movies from extratorrent

### ISSUE THREAD

**Issue by dr0ther** [msgprado/couchpotato.provider.extratorrent#2]
### Steps to reproduce:
1. Clicked to download the movie

### Information:
Movie(s) I have this with: ... James White
Quality of the movie being searched: ... DVDRip
Providers I use: ... ExtraTorrent
Version of CouchPotato: desktop: 3.0.1
Running on: ... Windows 7 Service Pack 1

### Logs:
```
12-11 11:18:03 ERROR [o.core.downloaders.deluge] Failed to add torrent file James.White.2015.DVDRip.x264-WiDEVR56.cp(tt4288636).torrent: not a valid bencoded string Traceback (most recent call last):
  File "C:\Users\MediaServer\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32\couchpotato\core\downloaders\deluge.py", line 255, in add_torrent_file
  File "C:\Users\MediaServer\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32\couchpotato\core\downloaders\deluge.py", line 319, in _check_torrent
  File "C:\Users\MediaServer\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32\libs\bencode\__init__.py", line 68, in bdecode
BTFailure: not a valid bencoded string
 
```

**Comment by msgprado** [comment]
Thanks for your reporting! main.py was out of date, but I quickly updated it and uploaded it. I Hope works now. Good downloading.
Remember:
- Delete all files in extratorrent folder and past the updated files.
- Restart CouchPotato.
